AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  TaskApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
  UsersTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: PK
        Type: String
  TasksTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: PK
        Type: String
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: auth.handler
      Runtime: python3.11
      Events:
        Login:
          Type: Api
          Properties:
            Path: /login
            Method: post
            RestApiId:
              Ref: TaskApi
